import path from "node:path";
import { PORTFOLIO_BRAIN_DIR, PROJECT_MEMORY_DIR } from "../../shared/constants.js";
import type {
  CreateSignalRequest,
  DecisionEvent,
  ProjectDetail,
  ProjectStatus,
  ProjectStatusRecord,
  ProjectSummary,
  Recommendation,
  SignalRecord,
  UpdateStatusRequest
} from "../../shared/domain.js";
import { DecisionEventSchema, ProjectStatusRecordSchema } from "../../shared/domain.js";
import { createId } from "../lib/ids.js";
import {
  appendJsonl,
  ensureDir,
  readJson,
  readJsonl,
  readText,
  writeJson,
  writeJsonl,
  writeMarkdown
} from "./fs-utils.js";
import { ingestArtifactSignals } from "./artifact-ingestion-service.js";
import { buildRepoHeuristics, buildRepoSignals } from "./repo-scanner.js";
import {
  createCodingAgentBriefMarkdown,
  createRecommendationMarkdown,
  createNextTaskMarkdown,
  generateRecommendations
} from "./recommendation-service.js";
import { generateLlmRationale, generateProjectThesis } from "./llm-rationale-service.js";
import { ingestPendingSignals } from "./pending-signal-service.js";

const memoryPath = (projectPath: string, ...parts: string[]): string =>
  path.join(projectPath, PROJECT_MEMORY_DIR, ...parts);

const brainPath = (projectPath: string, ...parts: string[]): string =>
  path.join(projectPath, PORTFOLIO_BRAIN_DIR, ...parts);

const defaultThesis = (projectName: string): string => `# Project Thesis

## Product
${projectName}

## User
(Who uses this and what problem do they have?)

## Current promise
(What does this project promise to deliver?)

## Drift warnings
- (What could pull this project off course?)
`;

const defaultStatus = (): ProjectStatusRecord => ({
  status: "active",
  activeRecommendationId: "",
  currentConfidence: 0,
  lastUpdatedAt: "",
  lastScannedAt: ""
});

const signalFileMap: Record<"feedback" | "note" | "idea", string> = {
  feedback: "user-feedback.jsonl",
  note: "notes-and-chats.jsonl",
  idea: "bugs-and-ideas.jsonl"
};

const CLAUDE_MD_MARKER_START = "<!-- AI-NATIVE-BACKLOG:START -->";
const CLAUDE_MD_MARKER_END = "<!-- AI-NATIVE-BACKLOG:END -->";

const buildClaudeMdSection = (): string =>
  [
    CLAUDE_MD_MARKER_START,
    "## AI-Native Project Backlog",
    "",
    "This project has an active memory workspace. Read it at the start of every session and write to it throughout.",
    "",
    "**Before starting work:**",
    "1. Read `.project-memory/tasks/next-task.md` — the specific next task",
    "2. Read `.project-memory/recommendations/current.md` — the recommendation and why",
    "3. Read `.project-memory/tasks/coding-agent-brief.md` — operating mode, thesis, constraints",
    "4. Skim `.project-memory/workspace/` — context and open items from past sessions",
    "",
    "**During the session, actively write to `.project-memory/workspace/`:**",
    "- Bugs found → append to `workspace/bugs.md` with a date stamp and what you found",
    "- Ideas that come up → append to `workspace/ideas.md`",
    "- Decisions made, things tried, what worked → append to `workspace/session-notes.md`",
    "- Completed tasks → append to `workspace/progress.md`",
    "",
    "Keep entries atomic and specific. Use markdown bullets. Date-stamp each entry.",
    "",
    "**Only write to `.portfolio-brain/signals/pending/` for portfolio-level events:**",
    "- A deploy blocker you cannot resolve yourself",
    "- Evidence the project thesis is wrong or the audience has shifted",
    "- A critical bug that changes the project's direction",
    "",
    "Signal format for `.portfolio-brain/signals/pending/<name>.jsonl`:",
    "```",
    '{"type": "note", "source": "claude-code", "summary": "...", "details": "..."}',
    "```",
    "Write to `<name>.tmp` first, then rename to `<name>.jsonl` (atomic write rule).",
    "",
    "**Do not widen scope** beyond the current recommendation unless fresh evidence justifies it.",
    CLAUDE_MD_MARKER_END
  ].join("\n");

const ensureClaudeMd = async (projectPath: string): Promise<void> => {
  const claudeMdPath = path.join(projectPath, "CLAUDE.md");
  const existing = await readText(claudeMdPath, "");
  const section = buildClaudeMdSection();

  if (existing.includes(CLAUDE_MD_MARKER_START)) {
    // Replace existing section in place
    const updated = existing.replace(
      new RegExp(`${CLAUDE_MD_MARKER_START}[\\s\\S]*?${CLAUDE_MD_MARKER_END}`),
      section
    );
    if (updated !== existing) {
      await writeMarkdown(claudeMdPath, updated);
    }
    return;
  }

  // Prepend section to existing content (or create fresh)
  const newContent = existing ? `${section}\n\n---\n\n${existing.trim()}` : section;
  await writeMarkdown(claudeMdPath, newContent);
};

const buildContextMd = (projectPath: string): string =>
  [
    "<!-- DO NOT EDIT — machine-generated by AI Native Project Backlog -->",
    "# Portfolio Brain Context",
    "",
    "This project is tracked by AI Native Project Backlog.",
    "",
    "Before starting work, read:",
    `- \`${PROJECT_MEMORY_DIR}/recommendations/current.md\``,
    `- \`${PROJECT_MEMORY_DIR}/tasks/next-task.md\``,
    "",
    "To add a signal from Claude Code, create a file in:",
    `\`${PORTFOLIO_BRAIN_DIR}/signals/pending/\``,
    "",
    "Signal format (.jsonl):",
    '```',
    '{"type": "note", "source": "claude-code", "summary": "What you found", "details": "Optional detail"}',
    '```',
    "",
    "Signal format (.md with frontmatter):",
    "```",
    "---",
    "type: feedback",
    "source: claude-code",
    "summary: What you found",
    "---",
    "Optional detail text here.",
    "```",
    "",
    "Valid types: `feedback`, `note`, `idea`",
    "",
    "**Atomic write rule:** Write to `<filename>.tmp` then rename to the final name.",
    `Files with \`.tmp\` extension are ignored by the watcher.`,
    "",
    `Path on disk: \`${projectPath}\``
  ].join("\n");

export const ensureProjectMemory = async (projectName: string, projectPath: string): Promise<void> => {
  await ensureDir(memoryPath(projectPath));
  await ensureDir(memoryPath(projectPath, "signals"));
  await ensureDir(memoryPath(projectPath, "recommendations"));
  await ensureDir(memoryPath(projectPath, "decisions"));
  await ensureDir(memoryPath(projectPath, "tasks"));
  await ensureDir(memoryPath(projectPath, "workspace"));

  // Ensure .portfolio-brain dirs
  await ensureDir(brainPath(projectPath, "signals", "pending"));
  await ensureDir(brainPath(projectPath, "signals", "processed"));
  await ensureDir(brainPath(projectPath, "signals", "errors"));

  // Always overwrite CONTEXT.md — it's machine-generated
  await writeMarkdown(brainPath(projectPath, "CONTEXT.md"), buildContextMd(projectPath));

  // Inject/update the project memory section in CLAUDE.md
  await ensureClaudeMd(projectPath);

  const thesisPath = memoryPath(projectPath, "project-thesis.md");
  const statusPath = memoryPath(projectPath, "project-status.json");
  const recommendationPath = memoryPath(projectPath, "recommendations", "current.md");
  const nextTaskPath = memoryPath(projectPath, "tasks", "next-task.md");
  const agentBriefPath = memoryPath(projectPath, "tasks", "coding-agent-brief.md");

  if (!(await readText(thesisPath, ""))) {
    const aiThesis = await generateProjectThesis(projectName, projectPath);
    await writeMarkdown(thesisPath, aiThesis ?? defaultThesis(projectName));
  }

  if (!(await readText(statusPath, ""))) {
    await writeJson(statusPath, defaultStatus());
  }

  if (!(await readText(recommendationPath, ""))) {
    await writeMarkdown(recommendationPath, "# Current Recommendation\n\nNothing generated yet.");
  }

  if (!(await readText(nextTaskPath, ""))) {
    await writeMarkdown(nextTaskPath, "# Next Task\n\nNothing generated yet.");
  }

  if (!(await readText(agentBriefPath, ""))) {
    await writeMarkdown(agentBriefPath, "# Coding Agent Brief\n\nNothing generated yet.");
  }

  // Workspace starter files — only created once, Claude Code owns them after that
  const workspaceFiles: Array<[string, string]> = [
    ["workspace/bugs.md", "# Bugs\n\nAppend bugs found during sessions. Format: `- YYYY-MM-DD: <what you found and where>`\n"],
    ["workspace/ideas.md", "# Ideas\n\nAppend ideas that come up during sessions. Format: `- YYYY-MM-DD: <idea and why>`\n"],
    ["workspace/session-notes.md", "# Session Notes\n\nAppend decisions, things tried, and what worked. Format: `- YYYY-MM-DD: <what happened>`\n"],
    ["workspace/progress.md", "# Progress\n\nAppend completed tasks. Format: `- YYYY-MM-DD: <what was done>`\n"]
  ];
  for (const [relativePath, content] of workspaceFiles) {
    if (!(await readText(memoryPath(projectPath, relativePath), ""))) {
      await writeMarkdown(memoryPath(projectPath, relativePath), content);
    }
  }
};

const readStatus = async (projectPath: string): Promise<ProjectStatusRecord> => {
  const raw = await readJson(memoryPath(projectPath, "project-status.json"), defaultStatus());
  return ProjectStatusRecordSchema.parse(raw);
};

const writeStatus = async (projectPath: string, status: ProjectStatusRecord): Promise<void> => {
  await writeJson(memoryPath(projectPath, "project-status.json"), status);
};

const readSignals = async (projectPath: string): Promise<SignalRecord[]> => {
  const [feedback, notes, ideas, repoSignals, artifactSignals] = await Promise.all([
    readJsonl<SignalRecord>(memoryPath(projectPath, "signals", "user-feedback.jsonl")),
    readJsonl<SignalRecord>(memoryPath(projectPath, "signals", "notes-and-chats.jsonl")),
    readJsonl<SignalRecord>(memoryPath(projectPath, "signals", "bugs-and-ideas.jsonl")),
    readJsonl<SignalRecord>(memoryPath(projectPath, "signals", "repo-events.jsonl")),
    readJsonl<SignalRecord>(memoryPath(projectPath, "signals", "artifact-events.jsonl"))
  ]);

  return [...feedback, ...notes, ...ideas, ...repoSignals, ...artifactSignals];
};

const writeRecommendations = async (
  projectPath: string,
  recommendations: Recommendation[],
  signals: SignalRecord[] = [],
  llmNextTask?: string
): Promise<void> => {
  await writeMarkdown(
    memoryPath(projectPath, "recommendations", "current.md"),
    createRecommendationMarkdown(recommendations)
  );
  await appendJsonl(memoryPath(projectPath, "recommendations", "history.jsonl"), {
    createdAt: new Date().toISOString(),
    recommendations
  });
  await writeMarkdown(
    memoryPath(projectPath, "tasks", "next-task.md"),
    createNextTaskMarkdown(recommendations, signals, llmNextTask)
  );
};

const readRecommendations = async (projectPath: string): Promise<Recommendation[]> => {
  const history = await readJsonl<{ createdAt: string; recommendations: Recommendation[] }>(
    memoryPath(projectPath, "recommendations", "history.jsonl")
  );
  return history.at(-1)?.recommendations ?? [];
};

const readDecisions = async (projectPath: string): Promise<DecisionEvent[]> => {
  const decisions = await readJsonl<DecisionEvent>(memoryPath(projectPath, "decisions", "history.jsonl"));
  return decisions.map((decision) => DecisionEventSchema.parse(decision));
};

export const refreshProjectMemory = async (
  rootPath: string,
  project: ProjectSummary
): Promise<ProjectDetail> => {
  await ensureProjectMemory(project.name, project.path);

  // Ingest pending signals from Claude Code before reading
  const pendingSignals = await ingestPendingSignals(project.id, project.path);
  for (const signal of pendingSignals) {
    const fileName = signalFileMap[signal.type as "feedback" | "note" | "idea"];
    if (fileName) {
      await appendJsonl(memoryPath(project.path, "signals", fileName), signal);
    }
  }

  const [heuristics, repoSignals, artifactSignals] = await Promise.all([
    buildRepoHeuristics(project.path),
    buildRepoSignals(project.id, project.path),
    ingestArtifactSignals(project.id, project.path)
  ]);

  await writeJsonl(memoryPath(project.path, "signals", "repo-events.jsonl"), repoSignals);
  await writeJsonl(memoryPath(project.path, "signals", "artifact-events.jsonl"), artifactSignals);

  const statusRecord = await readStatus(project.path);
  const signals = await readSignals(project.path);
  const recommendations = generateRecommendations(project.id, statusRecord.status, signals);
  const thesisMarkdown = await readText(memoryPath(project.path, "project-thesis.md"), defaultThesis(project.name));

  // Annotate top recommendation with heuristic summary, and preserve LLM rationale if present
  if (recommendations[0]) {
    const existingRecs = await readRecommendations(project.path);
    const existingTop = existingRecs[0];
    recommendations[0] = {
      ...recommendations[0],
      heuristicSummary: heuristics.heuristicSummary,
      ...(existingTop?.hasLlmRationale
        ? {
            rationale: existingTop.rationale,
            whatWouldChangeMind: existingTop.whatWouldChangeMind,
            hasLlmRationale: true
          }
        : {})
    };
  }

  statusRecord.activeRecommendationId = recommendations[0]?.id ?? "";
  statusRecord.currentConfidence = recommendations[0]?.confidence ?? 0;
  statusRecord.lastUpdatedAt = new Date().toISOString();
  statusRecord.lastScannedAt = new Date().toISOString();
  await writeStatus(project.path, statusRecord);
  await writeRecommendations(project.path, recommendations, signals);
  await writeMarkdown(
    memoryPath(project.path, "tasks", "coding-agent-brief.md"),
    createCodingAgentBriefMarkdown(project.name, thesisMarkdown, recommendations)
  );

  const updatedProject: ProjectSummary = {
    ...project,
    status: statusRecord.status,
    lastScannedAt: statusRecord.lastScannedAt,
    topRecommendationType: recommendations[0]?.actionType ?? "investigate",
    momentumScore: Math.round((recommendations[0]?.priorityScore ?? 0) * 100),
    reasonSnippet: recommendations[0]?.rationale ?? "No recommendation yet."
  };

  return {
    rootPath,
    project: updatedProject,
    thesisMarkdown,
    agentBriefMarkdown: await readText(memoryPath(project.path, "tasks", "coding-agent-brief.md"), ""),
    signals: signals.sort((left, right) => right.createdAt.localeCompare(left.createdAt)),
    recommendations,
    decisionHistory: await readDecisions(project.path),
    nextTaskMarkdown: await readText(memoryPath(project.path, "tasks", "next-task.md"), ""),
    updatedAt: new Date().toISOString()
  };
};

export const runProjectJudgment = async (
  rootPath: string,
  project: ProjectSummary
): Promise<ProjectDetail> => {
  const detail = await refreshProjectMemory(rootPath, project);

  const topRec = detail.recommendations[0];
  if (!topRec) return detail;

  const [heuristics, thesisMarkdown, statusRecord] = await Promise.all([
    buildRepoHeuristics(project.path),
    readText(memoryPath(project.path, "project-thesis.md"), ""),
    readStatus(project.path)
  ]);

  const llmResult = await generateLlmRationale(
    project.name,
    statusRecord.status,
    heuristics,
    thesisMarkdown,
    detail.signals.slice(0, 5)
  );

  if (!llmResult) {
    return detail;
  }

  const updatedRec: Recommendation = {
    ...topRec,
    rationale: llmResult.rationale,
    whatWouldChangeMind: llmResult.whatWouldChangeMind,
    hasLlmRationale: true
  };

  const updatedRecommendations = [updatedRec, ...detail.recommendations.slice(1)];
  await writeRecommendations(project.path, updatedRecommendations, detail.signals, llmResult.nextTask || undefined);

  return {
    ...detail,
    recommendations: updatedRecommendations,
    nextTaskMarkdown: await readText(memoryPath(project.path, "tasks", "next-task.md"), ""),
    project: {
      ...detail.project,
      reasonSnippet: llmResult.rationale.slice(0, 200)
    }
  };
};

export const appendManualSignal = async (
  rootPath: string,
  project: ProjectSummary,
  payload: CreateSignalRequest
): Promise<ProjectDetail> => {
  const signal: SignalRecord = {
    id: createId("sig"),
    type: payload.type,
    source: payload.source,
    summary: payload.summary,
    details: payload.details,
    evidenceRefs: [`manual:${payload.type}:${new Date().toISOString()}`],
    freshnessScore: 0.95,
    confidence: 0.92,
    createdAt: new Date().toISOString()
  };

  await appendJsonl(memoryPath(project.path, "signals", signalFileMap[payload.type]), signal);
  return refreshProjectMemory(rootPath, project);
};

export const updateProjectStatus = async (
  rootPath: string,
  project: ProjectSummary,
  payload: UpdateStatusRequest
): Promise<ProjectDetail> => {
  const currentStatus = await readStatus(project.path);
  const previousState = currentStatus.status;
  currentStatus.status = payload.status as ProjectStatus;
  currentStatus.lastUpdatedAt = new Date().toISOString();
  await writeStatus(project.path, currentStatus);

  const decision: DecisionEvent = {
    id: createId("decision"),
    actor: payload.actor,
    kind: "status-change",
    previousState,
    newState: payload.status,
    rationale: payload.rationale,
    evidenceRefs: [`status:${previousState}->${payload.status}`],
    createdAt: new Date().toISOString()
  };

  await appendJsonl(memoryPath(project.path, "decisions", "history.jsonl"), decision);
  return refreshProjectMemory(rootPath, project);
};

export const readProjectSnapshot = async (
  rootPath: string,
  project: ProjectSummary
): Promise<ProjectDetail> => refreshProjectMemory(rootPath, project);

export const readLatestRecommendations = async (projectPath: string): Promise<Recommendation[]> =>
  readRecommendations(projectPath);
